name: Main Build

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - edburns/dd-3016202-cargotracker-devoxx-be-2026-01
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: "17"
      - name: Cache Maven packages
        uses: actions/cache@v6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check formatting
        run: ./mvnw spotless:check

  build:
    runs-on: ubuntu-latest
    needs: [formatting]
    defaults:
      run:
        working-directory: demo
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: microsoft
          java-version: "17"
      - name: Cache Maven packages
        uses: actions/cache@v6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw clean package --file pom.xml
